// Auto-generated from SEBI Nifty100, NiftyMidcap150, NiftySmallcap500 lists
// Large Cap  = Nifty 100 (100 stocks)
// Mid Cap    = Nifty Midcap 150 (150 stocks, deduplicated)
// Small Cap  = Nifty Smallcap 500 (500 stocks, deduplicated)

const companyNames = {
  "ABB.NS": "ABB India Ltd.",
  "ADANIENSOL.NS": "Adani Energy Solutions Ltd.",
  "ADANIENT.NS": "Adani Enterprises Ltd.",
  "ADANIGREEN.NS": "Adani Green Energy Ltd.",
  "ADANIPORTS.NS": "Adani Ports and Special Economic Zone Ltd.",
  "ADANIPOWER.NS": "Adani Power Ltd.",
  "AMBUJACEM.NS": "Ambuja Cements Ltd.",
  "APOLLOHOSP.NS": "Apollo Hospitals Enterprise Ltd.",
  "ASIANPAINT.NS": "Asian Paints Ltd.",
  "DMART.NS": "Avenue Supermarts Ltd.",
  "AXISBANK.NS": "Axis Bank Ltd.",
  "BAJAJ-AUTO.NS": "Bajaj Auto Ltd.",
  "BAJFINANCE.NS": "Bajaj Finance Ltd.",
  "BAJAJFINSV.NS": "Bajaj Finserv Ltd.",
  "BAJAJHLDNG.NS": "Bajaj Holdings & Investment Ltd.",
  "BANKBARODA.NS": "Bank of Baroda",
  "BEL.NS": "Bharat Electronics Ltd.",
  "BPCL.NS": "Bharat Petroleum Corporation Ltd.",
  "BHARTIARTL.NS": "Bharti Airtel Ltd.",
  "BOSCHLTD.NS": "Bosch Ltd.",
  "BRITANNIA.NS": "Britannia Industries Ltd.",
  "CGPOWER.NS": "CG Power and Industrial Solutions Ltd.",
  "CANBK.NS": "Canara Bank",
  "CHOLAFIN.NS": "Cholamandalam Investment and Finance Company Ltd.",
  "CIPLA.NS": "Cipla Ltd.",
  "COALINDIA.NS": "Coal India Ltd.",
  "CUMMINSIND.NS": "Cummins India Ltd.",
  "DLF.NS": "DLF Ltd.",
  "DIVISLAB.NS": "Divi's Laboratories Ltd.",
  "DRREDDY.NS": "Dr. Reddy's Laboratories Ltd.",
  "EICHERMOT.NS": "Eicher Motors Ltd.",
  "ETERNAL.NS": "Eternal Ltd.",
  "GAIL.NS": "GAIL (India) Ltd.",
  "GODREJCP.NS": "Godrej Consumer Products Ltd.",
  "GRASIM.NS": "Grasim Industries Ltd.",
  "HCLTECH.NS": "HCL Technologies Ltd.",
  "HDFCAMC.NS": "HDFC Asset Management Company Ltd.",
  "HDFCBANK.NS": "HDFC Bank Ltd.",
  "HDFCLIFE.NS": "HDFC Life Insurance Company Ltd.",
  "HINDALCO.NS": "Hindalco Industries Ltd.",
  "HAL.NS": "Hindustan Aeronautics Ltd.",
  "HINDUNILVR.NS": "Hindustan Unilever Ltd.",
  "HINDZINC.NS": "Hindustan Zinc Ltd.",
  "HYUNDAI.NS": "Hyundai Motor India Ltd.",
  "ICICIBANK.NS": "ICICI Bank Ltd.",
  "ITC.NS": "ITC Ltd.",
  "INDHOTEL.NS": "Indian Hotels Co. Ltd.",
  "IOC.NS": "Indian Oil Corporation Ltd.",
  "IRFC.NS": "Indian Railway Finance Corporation Ltd.",
  "INFY.NS": "Infosys Ltd.",
  "INDIGO.NS": "InterGlobe Aviation Ltd.",
  "JSWSTEEL.NS": "JSW Steel Ltd.",
  "JINDALSTEL.NS": "Jindal Steel Ltd.",
  "JIOFIN.NS": "Jio Financial Services Ltd.",
  "KOTAKBANK.NS": "Kotak Mahindra Bank Ltd.",
  "LTM.NS": "LTIMindtree Ltd.",
  "LT.NS": "Larsen & Toubro Ltd.",
  "LODHA.NS": "Lodha Developers Ltd.",
  "M&M.NS": "Mahindra & Mahindra Ltd.",
  "MARUTI.NS": "Maruti Suzuki India Ltd.",
  "MAXHEALTH.NS": "Max Healthcare Institute Ltd.",
  "MAZDOCK.NS": "Mazagoan Dock Shipbuilders Ltd.",
  "MUTHOOTFIN.NS": "Muthoot Finance Ltd.",
  "NTPC.NS": "NTPC Ltd.",
  "NESTLEIND.NS": "Nestle India Ltd.",
  "ONGC.NS": "Oil & Natural Gas Corporation Ltd.",
  "PIDILITIND.NS": "Pidilite Industries Ltd.",
  "PFC.NS": "Power Finance Corporation Ltd.",
  "POWERGRID.NS": "Power Grid Corporation of India Ltd.",
  "PNB.NS": "Punjab National Bank",
  "RECLTD.NS": "REC Ltd.",
  "RELIANCE.NS": "Reliance Industries Ltd.",
  "SBILIFE.NS": "SBI Life Insurance Company Ltd.",
  "MOTHERSON.NS": "Samvardhana Motherson International Ltd.",
  "SHREECEM.NS": "Shree Cement Ltd.",
  "SHRIRAMFIN.NS": "Shriram Finance Ltd.",
  "ENRIN.NS": "Siemens Energy India Ltd.",
  "SIEMENS.NS": "Siemens Ltd.",
  "SOLARINDS.NS": "Solar Industries India Ltd.",
  "SBIN.NS": "State Bank of India",
  "SUNPHARMA.NS": "Sun Pharmaceutical Industries Ltd.",
  "TVSMOTOR.NS": "TVS Motor Company Ltd.",
  "TATACAP.NS": "Tata Capital Ltd.",
  "TCS.NS": "Tata Consultancy Services Ltd.",
  "TATACONSUM.NS": "Tata Consumer Products Ltd.",
  "TMCV.NS": "Tata Motors Ltd.",
  "TMPV.NS": "Tata Motors Passenger Vehicles Ltd.",
  "TATAPOWER.NS": "Tata Power Co. Ltd.",
  "TATASTEEL.NS": "Tata Steel Ltd.",
  "TECHM.NS": "Tech Mahindra Ltd.",
  "TITAN.NS": "Titan Company Ltd.",
  "TORNTPHARM.NS": "Torrent Pharmaceuticals Ltd.",
  "TRENT.NS": "Trent Ltd.",
  "ULTRACEMCO.NS": "UltraTech Cement Ltd.",
  "UNIONBANK.NS": "Union Bank of India",
  "UNITDSPR.NS": "United Spirits Ltd.",
  "VBL.NS": "Varun Beverages Ltd.",
  "VEDL.NS": "Vedanta Ltd.",
  "WIPRO.NS": "Wipro Ltd.",
  "ZYDUSLIFE.NS": "Zydus Lifesciences Ltd.",
};

const largeCap = new Set([
  "ABB.NS",
  "ADANIENSOL.NS",
  "ADANIENT.NS",
  "ADANIGREEN.NS",
  "ADANIPORTS.NS",
  "ADANIPOWER.NS",
  "AMBUJACEM.NS",
  "APOLLOHOSP.NS",
  "ASIANPAINT.NS",
  "DMART.NS",
  "AXISBANK.NS",
  "BAJAJ-AUTO.NS",
  "BAJFINANCE.NS",
  "BAJAJFINSV.NS",
  "BAJAJHLDNG.NS",
  "BANKBARODA.NS",
  "BEL.NS",
  "BPCL.NS",
  "BHARTIARTL.NS",
  "BOSCHLTD.NS",
  "BRITANNIA.NS",
  "CGPOWER.NS",
  "CANBK.NS",
  "CHOLAFIN.NS",
  "CIPLA.NS",
  "COALINDIA.NS",
  "CUMMINSIND.NS",
  "DLF.NS",
  "DIVISLAB.NS",
  "DRREDDY.NS",
  "EICHERMOT.NS",
  "ETERNAL.NS",
  "GAIL.NS",
  "GODREJCP.NS",
  "GRASIM.NS",
  "HCLTECH.NS",
  "HDFCAMC.NS",
  "HDFCBANK.NS",
  "HDFCLIFE.NS",
  "HINDALCO.NS",
  "HAL.NS",
  "HINDUNILVR.NS",
  "HINDZINC.NS",
  "HYUNDAI.NS",
  "ICICIBANK.NS",
  "ITC.NS",
  "INDHOTEL.NS",
  "IOC.NS",
  "IRFC.NS",
  "INFY.NS",
  "INDIGO.NS",
  "JSWSTEEL.NS",
  "JINDALSTEL.NS",
  "JIOFIN.NS",
  "KOTAKBANK.NS",
  "LTM.NS",
  "LT.NS",
  "LODHA.NS",
  "M&M.NS",
  "MARUTI.NS",
  "MAXHEALTH.NS",
  "MAZDOCK.NS",
  "MUTHOOTFIN.NS",
  "NTPC.NS",
  "NESTLEIND.NS",
  "ONGC.NS",
  "PIDILITIND.NS",
  "PFC.NS",
  "POWERGRID.NS",
  "PNB.NS",
  "RECLTD.NS",
  "RELIANCE.NS",
  "SBILIFE.NS",
  "MOTHERSON.NS",
  "SHREECEM.NS",
  "SHRIRAMFIN.NS",
  "ENRIN.NS",
  "SIEMENS.NS",
  "SOLARINDS.NS",
  "SBIN.NS",
  "SUNPHARMA.NS",
  "TVSMOTOR.NS",
  "TATACAP.NS",
  "TCS.NS",
  "TATACONSUM.NS",
  "TMCV.NS",
  "TMPV.NS",
  "TATAPOWER.NS",
  "TATASTEEL.NS",
  "TECHM.NS",
  "TITAN.NS",
  "TORNTPHARM.NS",
  "TRENT.NS",
  "ULTRACEMCO.NS",
  "UNIONBANK.NS",
  "UNITDSPR.NS",
  "VBL.NS",
  "VEDL.NS",
  "WIPRO.NS",
  "ZYDUSLIFE.NS",
]);

const midCap = new Set([
  "360ONE.NS",
  "3MINDIA.NS",
  "ACC.NS",
  "AIAENG.NS",
  "APLAPOLLO.NS",
  "AUBANK.NS",
  "AWL.NS",
  "ABBOTINDIA.NS",
  "ATGL.NS",
  "ABCAPITAL.NS",
  "AJANTPHARM.NS",
  "ALKEM.NS",
  "ANTHEM.NS",
  "APARINDS.NS",
  "APOLLOTYRE.NS",
  "ASHOKLEY.NS",
  "ASTRAL.NS",
  "AUROPHARMA.NS",
  "AIIL.NS",
  "BSE.NS",
  "BAJAJHFL.NS",
  "BALKRISIND.NS",
  "BANKINDIA.NS",
  "MAHABANK.NS",
  "BERGEPAINT.NS",
  "BDL.NS",
  "BHARATFORG.NS",
  "BHEL.NS",
  "BHARTIHEXA.NS",
  "GROWW.NS",
  "BIOCON.NS",
  "BLUESTARCO.NS",
  "CRISIL.NS",
  "COCHINSHIP.NS",
  "COFORGE.NS",
  "COLPAL.NS",
  "CONCOR.NS",
  "COROMANDEL.NS",
  "DABUR.NS",
  "DALBHARAT.NS",
  "DIXON.NS",
  "ENDURANCE.NS",
  "ESCORTS.NS",
  "EXIDEIND.NS",
  "NYKAA.NS",
  "FEDERALBNK.NS",
  "FORTIS.NS",
  "GVT&D.NS",
  "GMRAIRPORT.NS",
  "GICRE.NS",
  "GLAXO.NS",
  "GLENMARK.NS",
  "MEDANTA.NS",
  "GODFRYPHLP.NS",
  "GODREJIND.NS",
  "GODREJPROP.NS",
  "FLUOROCHEM.NS",
  "HDBFS.NS",
  "HAVELLS.NS",
  "HEROMOTOCO.NS",
  "HEXT.NS",
  "HINDPETRO.NS",
  "POWERINDIA.NS",
  "HONAUT.NS",
  "HUDCO.NS",
  "ICICIGI.NS",
  "ICICIAMC.NS",
  "ICICIPRULI.NS",
  "IDFCFIRSTB.NS",
  "ITCHOTELS.NS",
  "INDIANB.NS",
  "IRCTC.NS",
  "IREDA.NS",
  "INDUSTOWER.NS",
  "INDUSINDBK.NS",
  "NAUKRI.NS",
  "IPCALAB.NS",
  "JKCEMENT.NS",
  "JSWENERGY.NS",
  "JSWINFRA.NS",
  "JSL.NS",
  "JUBLFOOD.NS",
  "KPRMILL.NS",
  "KEI.NS",
  "KPITTECH.NS",
  "KALYANKJIL.NS",
  "LTF.NS",
  "LTTS.NS",
  "LGEINDIA.NS",
  "LICHSGFIN.NS",
  "LAURUSLABS.NS",
  "LENSKART.NS",
  "LICI.NS",
  "LINDEINDIA.NS",
  "LLOYDSME.NS",
  "LUPIN.NS",
  "MRF.NS",
  "M&MFIN.NS",
  "MANKIND.NS",
  "MARICO.NS",
  "MFSL.NS",
  "MOTILALOFS.NS",
  "MPHASIS.NS",
  "MCX.NS",
  "NHPC.NS",
  "NLCINDIA.NS",
  "NMDC.NS",
  "NTPCGREEN.NS",
  "NATIONALUM.NS",
  "NAM-INDIA.NS",
  "OBEROIRLTY.NS",
  "OIL.NS",
  "PAYTM.NS",
  "OFSS.NS",
  "POLICYBZR.NS",
  "PIIND.NS",
  "PAGEIND.NS",
  "PATANJALI.NS",
  "PERSISTENT.NS",
  "PETRONET.NS",
  "PHOENIXLTD.NS",
  "POLYCAB.NS",
  "PREMIERENE.NS",
  "PRESTIGE.NS",
  "RADICO.NS",
  "RVNL.NS",
  "SBICARD.NS",
  "SJVN.NS",
  "SRF.NS",
  "SCHAEFFLER.NS",
  "SAIL.NS",
  "SUNDARMFIN.NS",
  "SUPREMEIND.NS",
  "SUZLON.NS",
  "SWIGGY.NS",
  "TATACOMM.NS",
  "TATAELXSI.NS",
  "TATAINVEST.NS",
  "NIACL.NS",
  "THERMAX.NS",
  "TORNTPOWER.NS",
  "TIINDIA.NS",
  "UNOMINDA.NS",
  "UPL.NS",
  "UBL.NS",
  "VMM.NS",
  "IDEA.NS",
  "VOLTAS.NS",
  "WAAREEENER.NS",
  "YESBANK.NS",
]);

const smallCap = new Set([
  "ACMESOLAR.NS",
  "ASKAUTOLTD.NS",
  "AXISCADES.NS",
  "AADHARHFC.NS",
  "AARTIDRUGS.NS",
  "AARTIIND.NS",
  "AARTIPHARM.NS",
  "AAVAS.NS",
  "ACE.NS",
  "ACUTAAS.NS",
  "ABFRL.NS",
  "ABLBL.NS",
  "ABREL.NS",
  "ABSLAMC.NS",
  "CPPLUS.NS",
  "AVL.NS",
  "ADVENZYMES.NS",
  "AEGISLOG.NS",
  "AEGISVOPAK.NS",
  "AEQUS.NS",
  "AETHER.NS",
  "AFCONS.NS",
  "AFFLE.NS",
  "AHLUCONT.NS",
  "AKUMS.NS",
  "AKZOINDIA.NS",
  "APLLTD.NS",
  "ALIVUS.NS",
  "ALKYLAMINE.NS",
  "ABDL.NS",
  "ALOKINDS.NS",
  "ARE&M.NS",
  "AMBER.NS",
  "ANANDRATHI.NS",
  "ANANTRAJ.NS",
  "ANGELONE.NS",
  "ANURAS.NS",
  "APOLLO.NS",
  "APTUS.NS",
  "ACI.NS",
  "ARVINDFASN.NS",
  "ARVIND.NS",
  "ASAHIINDIA.NS",
  "ASHAPURMIN.NS",
  "ASHOKA.NS",
  "ASTERDM.NS",
  "ASTRAMICRO.NS",
  "ASTRAZEN.NS",
  "ATHERENERG.NS",
  "ATLANTAELE.NS",
  "ATUL.NS",
  "AURIONPRO.NS",
  "AVALON.NS",
  "AVANTIFEED.NS",
  "CCAVENUE.NS",
  "AWFIS.NS",
  "AZAD.NS",
  "BEML.NS",
  "BLS.NS",
  "BAJAJELEC.NS",
  "BALAMINES.NS",
  "BALRAMCHIN.NS",
  "BALUFORGE.NS",
  "BANCOINDIA.NS",
  "BANDHANBNK.NS",
  "BATAINDIA.NS",
  "BAYERCROP.NS",
  "BELRISE.NS",
  "BIKAJI.NS",
  "BIRLACORPN.NS",
  "BSOFT.NS",
  "BBOX.NS",
  "BLACKBUCK.NS",
  "BLUEDART.NS",
  "BLUEJET.NS",
  "BLUESTONE.NS",
  "BBTC.NS",
  "BORORENEW.NS",
  "FIRSTCRY.NS",
  "BRIGADE.NS",
  "MAPMYINDIA.NS",
  "CCL.NS",
  "CESC.NS",
  "CIEINDIA.NS",
  "CMSINFO.NS",
  "CSBBANK.NS",
  "CAMPUS.NS",
  "CANFINHOME.NS",
  "CANHLIFE.NS",
  "CRAMC.NS",
  "CAPILLARY.NS",
  "CAPLIPOINT.NS",
  "CGCL.NS",
  "CARBORUNIV.NS",
  "CARTRADE.NS",
  "CASTROLIND.NS",
  "CEATLTD.NS",
  "CELLO.NS",
  "CEMPRO.NS",
  "CENTRALBK.NS",
  "CDSL.NS",
  "CENTURYPLY.NS",
  "CERA.NS",
  "CHALET.NS",
  "CHAMBLFERT.NS",
  "CHENNPETRO.NS",
  "CHOICEIN.NS",
  "CHOLAHLDNG.NS",
  "CIGNITITEC.NS",
  "CUB.NS",
  "CLEAN.NS",
  "COHANCE.NS",
  "CAMS.NS",
  "CONCORDBIO.NS",
  "CRAFTSMAN.NS",
  "CREDITACC.NS",
  "CROMPTON.NS",
  "CUPID.NS",
  "CYIENT.NS",
  "DCBBANK.NS",
  "DCMSHRIRAM.NS",
  "DOMS.NS",
  "DATAPATTNS.NS",
  "DATAMATICS.NS",
  "DEEPAKFERT.NS",
  "DEEPAKNTR.NS",
  "DELHIVERY.NS",
  "DEVYANI.NS",
  "DIACABS.NS",
  "DBL.NS",
  "AGARWALEYE.NS",
  "LALPATHLAB.NS",
  "DYNAMATECH.NS",
  "EIDPARRY.NS",
  "EIHOTEL.NS",
  "EPL.NS",
  "EDELWEISS.NS",
  "ELECON.NS",
  "EMIL.NS",
  "ELECTCAST.NS",
  "ELGIEQUIP.NS",
  "ELLEN.NS",
  "EMAMILTD.NS",
  "EMBDL.NS",
  "EMCURE.NS",
  "EMMVEE.NS",
  "ENGINERSIN.NS",
  "ENTERO.NS",
  "EQUITASBNK.NS",
  "ERIS.NS",
  "ETHOSLTD.NS",
  "EUREKAFORB.NS",
  "FEDFINA.NS",
  "FACT.NS",
  "FIEMIND.NS",
  "FINCABLES.NS",
  "FINPIPE.NS",
  "FSL.NS",
  "FIVESTAR.NS",
  "FORCEMOT.NS",
  "UTLSOLAR.NS",
  "GHCL.NS",
  "GMMPFAUDLR.NS",
  "GMRP&UI.NS",
  "GABRIEL.NS",
  "GALLANTT.NS",
  "GRSE.NS",
  "GRWRHITECH.NS",
  "GILLETTE.NS",
  "GLAND.NS",
  "GODIGIT.NS",
  "GPIL.NS",
  "GODREJAGRO.NS",
  "GOKEX.NS",
  "GOKULAGRO.NS",
  "GRANULES.NS",
  "GRAPHITE.NS",
  "GRAVITA.NS",
  "GESHIP.NS",
  "GREAVESCOT.NS",
  "GAEL.NS",
  "GUJGASLTD.NS",
  "GMDCLTD.NS",
  "GNFC.NS",
  "GPPL.NS",
  "GSFC.NS",
  "GSPL.NS",
  "HEG.NS",
  "HGINFRA.NS",
  "HBLENGINE.NS",
  "HFCL.NS",
  "HAPPSTMNDS.NS",
  "HATSUN.NS",
  "HCG.NS",
  "HEMIPROP.NS",
  "HERITGFOOD.NS",
  "HSCL.NS",
  "HCC.NS",
  "HINDCOPPER.NS",
  "HOMEFIRST.NS",
  "HONASA.NS",
  "IDBI.NS",
  "IFBIND.NS",
  "IFCI.NS",
  "IIFLCAPS.NS",
  "IIFL.NS",
  "INOXINDIA.NS",
  "IRB.NS",
  "IRCON.NS",
  "ITI.NS",
  "INDGN.NS",
  "INDIACEM.NS",
  "INDIAGLYCO.NS",
  "INDIASHLTR.NS",
  "INDIAMART.NS",
  "IEX.NS",
  "IMFA.NS",
  "IOB.NS",
  "INDIGOPNTS.NS",
  "ICIL.NS",
  "IGL.NS",
  "INOXGREEN.NS",
  "INOXWIND.NS",
  "INTELLECT.NS",
  "IGIL.NS",
  "IKS.NS",
  "IONEXCHANG.NS",
  "JBCHEPHARM.NS",
  "JBMA.NS",
  "JKLAKSHMI.NS",
  "JKPAPER.NS",
  "JKTYRE.NS",
  "JMFINANCIL.NS",
  "JSWCEMENT.NS",
  "JAIBALAJI.NS",
  "JAINREC.NS",
  "JPPOWER.NS",
  "J&KBANK.NS",
  "JAMNAAUTO.NS",
  "JSFB.NS",
  "JAYNECOIND.NS",
  "JSLL.NS",
  "JINDALSAW.NS",
  "JUBLINGREA.NS",
  "JUBLPHARMA.NS",
  "JLHL.NS",
  "JWL.NS",
  "JUSTDIAL.NS",
  "JYOTHYLAB.NS",
  "JYOTICNC.NS",
  "KNRCON.NS",
  "KPIGREEN.NS",
  "KRBL.NS",
  "KRN.NS",
  "KSB.NS",
  "KAJARIACER.NS",
  "KPIL.NS",
  "KANSAINER.NS",
  "KTKBANK.NS",
  "KARURVYSYA.NS",
  "KSCL.NS",
  "KAYNES.NS",
  "KEC.NS",
  "KFINTECH.NS",
  "KIRLOSBROS.NS",
  "KIRLOSENG.NS",
  "KIRLPNU.NS",
  "KIMS.NS",
  "LTFOODS.NS",
  "LATENTVIEW.NS",
  "LXCHEM.NS",
  "IXIGO.NS",
  "THELEELA.NS",
  "LEMONTREE.NS",
  "LLOYDSENGG.NS",
  "LLOYDSENT.NS",
  "LUMAXTECH.NS",
  "MMTC.NS",
  "MOIL.NS",
  "MSTCLTD.NS",
  "MTARTECH.NS",
  "MGL.NS",
  "MAHSCOOTER.NS",
  "MAHSEAMLES.NS",
  "MANAPPURAM.NS",
  "MRPL.NS",
  "MANORAMA.NS",
  "MARKSANS.NS",
  "MASTEK.NS",
  "MEDPLUS.NS",
  "MEESHO.NS",
  "METROBRAND.NS",
  "METROPOLIS.NS",
  "MINDACORP.NS",
  "MIDHANI.NS",
  "MSUMI.NS",
  "BECTORFOOD.NS",
  "NATCOPHARM.NS",
  "NBCC.NS",
  "NCC.NS",
  "NEOGEN.NS",
  "NESCO.NS",
  "NSLNISP.NS",
  "NH.NS",
  "NFL.NS",
  "NAVA.NS",
  "NAVINFLUOR.NS",
  "NAZARA.NS",
  "NETWEB.NS",
  "NETWORK18.NS",
  "NEULANDLAB.NS",
  "NEWGEN.NS",
  "NIVABUPA.NS",
  "NUVAMA.NS",
  "NUVOCO.NS",
  "OLAELEC.NS",
  "OLECTRA.NS",
  "ONESOURCE.NS",
  "OPTIEMUS.NS",
  "ORIENTCEM.NS",
  "ORKLAINDIA.NS",
  "OSWALPUMPS.NS",
  "PNGJL.NS",
  "PCJEWELLER.NS",
  "PCBL.NS",
  "PGEL.NS",
  "PNBHOUSING.NS",
  "PNCINFRA.NS",
  "PTC.NS",
  "PTCIL.NS",
  "PVRINOX.NS",
  "PARADEEP.NS",
  "PARAS.NS",
  "PGIL.NS",
  "PFIZER.NS",
  "PWL.NS",
  "PICCADIL.NS",
  "PINELABS.NS",
  "PIRAMALFIN.NS",
  "PPLPHARMA.NS",
  "POLYMED.NS",
  "POONAWALLA.NS",
  "POWERMECH.NS",
  "PRAJIND.NS",
  "PRICOLLTD.NS",
  "PFOCUS.NS",
  "PRSMJOHNSN.NS",
  "PRIVISCL.NS",
  "PRUDENT.NS",
  "PURVA.NS",
  "QPOWER.NS",
  "QUESS.NS",
  "RRKABEL.NS",
  "RSYSTEMS.NS",
  "RBLBANK.NS",
  "RHIM.NS",
  "RITES.NS",
  "RAILTEL.NS",
  "RAIN.NS",
  "RAINBOW.NS",
  "RALLIS.NS",
  "RKFORGE.NS",
  "RCF.NS",
  "RATEGAIN.NS",
  "RTNINDIA.NS",
  "RTNPOWER.NS",
  "RAYMONDLSL.NS",
  "RAYMOND.NS",
  "RAYMONDREL.NS",
  "REDINGTON.NS",
  "REDTAPE.NS",
  "REFEX.NS",
  "RELAXO.NS",
  "RPOWER.NS",
  "RELIGARE.NS",
  "RBA.NS",
  "ROUTE.NS",
  "RUBICON.NS",
  "SBFC.NS",
  "SKFINDUS.NS",
  "SKFINDIA.NS",
  "SAATVIKGL.NS",
  "SAFARI.NS",
  "SAGILITY.NS",
  "SAILIFE.NS",
  "SAMHI.NS",
  "SAMMAANCAP.NS",
  "SANDUMA.NS",
  "SANSERA.NS",
  "SAPPHIRE.NS",
  "SARDAEN.NS",
  "SAREGAMA.NS",
  "SCHNEIDER.NS",
  "SENCO.NS",
  "SHAILY.NS",
  "SHAKTIPUMP.NS",
  "SHARDACROP.NS",
  "SFL.NS",
  "SHILPAMED.NS",
  "SCI.NS",
  "RENUKA.NS",
  "SHRIPISTON.NS",
  "SHYAMMETL.NS",
  "SIGNATURE.NS",
  "SKIPPER.NS",
  "SMARTWORKS.NS",
  "SOBHA.NS",
  "SONACOMS.NS",
  "SONATSOFTW.NS",
  "SOUTHBANK.NS",
  "LOTUSDEV.NS",
  "STARCEMENT.NS",
  "STARHEALTH.NS",
  "SWSOLAR.NS",
  "STLTECH.NS",
  "STAR.NS",
  "STYRENIX.NS",
  "SUBROS.NS",
  "SUDARSCHEM.NS",
  "SUDEEPPHRM.NS",
  "SUMICHEM.NS",
  "SPARC.NS",
  "SUNTV.NS",
  "SUNDRMFAST.NS",
  "SUNTECK.NS",
  "SPLPETRO.NS",
  "SUPRIYA.NS",
  "SURYAROSNI.NS",
  "SWANCORP.NS",
  "SYNGENE.NS",
  "SYRMA.NS",
  "TARC.NS",
  "TBOTEK.NS",
  "TDPOWERSYS.NS",
  "TSFINV.NS",
  "TVSHLTD.NS",
  "TVSSCS.NS",
  "TMB.NS",
  "TANLA.NS",
  "TATACHEM.NS",
  "TATATECH.NS",
  "TTML.NS",
  "TECHNOE.NS",
  "TEGA.NS",
  "TEJASNET.NS",
  "TENNIND.NS",
  "TEXRAIL.NS",
  "THANGAMAYL.NS",
  "ANUP.NS",
  "RAMCOCEM.NS",
  "THOMASCOOK.NS",
  "THYROCARE.NS",
  "TI.NS",
  "TIMETECHNO.NS",
  "TIMKEN.NS",
  "TIPSMUSIC.NS",
  "TITAGARH.NS",
  "TARIL.NS",
  "TRANSRAILL.NS",
  "TRAVELFOOD.NS",
  "TRIDENT.NS",
  "TRIVENI.NS",
  "TRITURBINE.NS",
  "UCOBANK.NS",
  "UTIAMC.NS",
  "UJJIVANSFB.NS",
  "URBANCO.NS",
  "USHAMART.NS",
  "VGUARD.NS",
  "VMART.NS",
  "VIPIND.NS",
  "V2RETAIL.NS",
  "WABAG.NS",
  "VAIBHAVGBL.NS",
  "DBREALTY.NS",
  "VTL.NS",
  "VARROC.NS",
  "MANYAVAR.NS",
  "VIJAYA.NS",
  "VIKRAMSOLR.NS",
  "VIYASH.NS",
  "VOLTAMP.NS",
  "WAAREERTL.NS",
  "WAKEFIT.NS",
  "WEWORK.NS",
  "WEBELSOLAR.NS",
  "WELCORP.NS",
  "WELENT.NS",
  "WELSPUNLIV.NS",
  "WESTLIFE.NS",
  "WHIRLPOOL.NS",
  "WOCKPHARMA.NS",
  "YATHARTH.NS",
  "ZFCVINDIA.NS",
  "ZAGGLE.NS",
  "ZEEL.NS",
  "ZENTEC.NS",
  "ZENSARTECH.NS",
  "ZYDUSWELL.NS",
  "ECLERX.NS",
]);

function normalizeSymbol(symbol) {
  let s = symbol.toUpperCase().trim();
  if (!s.endsWith(".NS") && !s.endsWith(".BO")) s += ".NS";
  return s;
}

function getStockCategory(symbol) {
  const s = normalizeSymbol(symbol);
  if (largeCap.has(s)) return "Large Cap";
  if (midCap.has(s))   return "Mid Cap";
  if (smallCap.has(s)) return "Small Cap";
  return "Unclassified"; // not found in any SEBI list
}

function getCompanyName(symbol) {
  const s = normalizeSymbol(symbol);
  return companyNames[s] || null;
}

function isKnownSymbol(symbol) {
  const s = normalizeSymbol(symbol);
  return largeCap.has(s) || midCap.has(s) || smallCap.has(s);
}

module.exports = { getStockCategory, getCompanyName, isKnownSymbol, normalizeSymbol };

